### ISSUE TITLE
Possibility to not check the read-only part of the buffer

### ISSUE THREAD

**Issue by Thaodan** [minad/jinx#107]
I'm using Jinx with IRC(Circe) and noticed that also the content that is not written by me is checked  as compared to flyspell where it was not the case.

Would it be possible to restrict the content that is checked by excluding read-only parts of the buffer?

**Comment by minad** [comment]
Circe probably defines a flyspell-mode-predicate. You can use one of the `jinx-exclude-*` variables to exclude regions which should not be checked. As you suggest, adding a predicate which excludes read-only regions might make sense, see `jinx--predicates`.

**Comment by Thaodan** [comment]
> As you suggest, adding a predicate which excludes read-only regions might make sense, see jinx--predicates.

Why close the issue then?

**Comment by minad** [comment]
The idea is that you can configure this in your user configuration. Jinx supplies configurations for many builtin Emacs packages but I don't intend to provide configurations which go beyond that.

**Comment by Thaodan** [comment]
I think it would be a good to default to ignore read-only content by default.

**Comment by minad** [comment]
Yes, maybe. I am unsure if such a read-only predicate is generally the right thing to do. Please try it in your configuration and let me know if it works well, across a variety of packages. I wonder why Circe buffers are checked in the first place, I think Jinx shouldn't be enabled there by default there since Circe is probably a `special-mode`? You probably added `jinx-mode` to the `circe-mode-hook` explicitly?

I'd need to investigate other packages with a similar character. So far I hadn't big issues with the current defaults (`global-jinx-mode`), but my set of installed packages is also not that extensive. Time will tell. Furthermore Jinx is not yet that widely used, so I have to wait for more feedback anyway.

**Comment by Thaodan** [comment]
> Circe probably defines a `flyspell-mode-predicate`.

I checked, circe doesn't define such a predicate.

**Comment by Thaodan** [comment]
> I wonder why Circe buffers are checked in the first place, I think Jinx shouldn't be enabled there by default there since Circe is probably a `special-mode`? You probably added `jinx-mode` to the `circe-mode-hook` explicitly?

I enabled Jinx in all modes I enabled Flyspell before. Circe uses lui.el for it's interface, I added jinx-mode to it's hook.

**Comment by minad** [comment]
> I enabled Jinx in all modes I enabled Flyspell before. Circe uses lui.el for it's interface, I added jinx-mode to it's hook.

Thanks, that's good to hear. Any other issues besides Circe? I looked at the Circe source and as suspected, there is a Flyspell-specific predicate. See https://github.com/emacs-circe/circe/blob/920ed78499c8967ef75912e9ff1247b8d19e1cee/circe.el#L1658-L1669.

For Jinx you should do the same and register your predicate in `jinx--predicates`. The situation is a little unfortunate and inconvenient, since it requires intervention by the user.

Initially I reused Flyspell predicates, but removed support after some time since it turned out that some predicates didn't meet the performance requirements of Jinx, notably the predicate provided by Org which is O(n) in the size of the buffer. See https://github.com/minad/jinx/commit/d7ab805bf73e5972b3d2718687be724e0e0a8112.

**Comment by Thaodan** [comment]
> Thanks, that's good to hear. Any other issues besides Circe? I looked at the Circe source and as suspected, there is a Flyspell-specific predicate. See https://github.com/emacs-circe/circe/blob/920ed78499c8967ef75912e9ff1247b8d19e1cee/circe.el#L1658-L1669.

That is only for usernames but it probably helps to. 

I checked flyspell it set `inhibit-read-only` does this relate to read-only text?

**Comment by minad** [comment]
No, let-binding `inhibit-read-only` allows the wrapped code to modify read-only text/buffers. A read-only predicate would have to check the `read-only` text property. This predicate should do it:

~~~ elisp
(defun jinx--read-only-p (start)
  (get-text-property start 'read-only))
(add-to-list 'jinx--predicates #'jinx--read-only-p)
~~~

**Comment by Thaodan** [comment]
> Initially I reused Flyspell predicates, but removed support after some time since it turned out that some predicates didn't meet the performance requirements of Jinx, notably the predicate provided by Org which is O(n) in the size of the buffer. See [d7ab805](https://github.com/minad/jinx/commit/d7ab805bf73e5972b3d2718687be724e0e0a8112).

Hm I know why you removed the feature however some might be very useful to reuse.
Do Jinx predicates work the same way as flyspell predicates?

**Comment by Thaodan** [comment]
> A read-only predicate would have to check the `read-only` text property.
Oh that makes sense, it's the first time I hear of those.

**Comment by minad** [comment]
> Hm I know why you removed the feature however some might be very useful to reuse.

Of course I agree. The problem is that I would then have to maintain an explicit allow list of working predicates. Then it is just easier to only use my own predicates which meet the requirements. Iirc I also reported the issue to the Org developers, but it seemed that there wasn't interest or it wasn't easily possible to improve performance.

> Do Jinx predicates work the same way as flyspell predicates?

Not exactly iirc. You can check the aforementioned commit for the adapter from Flyspell to Jinx predicate. You could of course also add that to your config. We could also document the adapter in the Jinx wiki (with a warning about potential performance problems).

**Comment by minad** [comment]
> > A read-only predicate would have to check the `read-only` text property.
> 
> Oh that makes sense, it's the first time I hear of those.

I thought you meant that in your initial message :)

> Would it be possible to restrict the content that is checked by excluding read-only parts of the buffer?
