### ISSUE TITLE
`jinx-correct` can't work in read-only buffer

### ISSUE THREAD

**Issue by stardiviner** [minad/jinx#11]
When I execute command `jinx-correct` in `*elfeed-entry*` (read-only) buffer. I got message:
```
command-execute: Buffer is read-only: #<buffer *elfeed-entry*>
```

**Comment by ashton314** [comment]
It's a read-only buffer—could you describe what you want to happen?

You can toggle the read-only status of a buffer with `C-x C-q` (`read-only-mode`). Does that fix the problem?

**Comment by stardiviner** [comment]
@ashton314 I want to mark the misspelled word as correct word in a read-only buffer. I think the command `jinx-correct` code should adjust the order of "interactive prompt a list of available correct words" and "save the misspelled word into personal dirctionary".

**Comment by minad** [comment]
I don't want to solve this, since `global-jinx-mode` is usually also disabled by default in read-only buffers. You can easily add such a command to your configuration.

~~~ elisp
(defun jinx-correct-all-read-only ()
  (interactive)
  (jinx-correct t))
~~~

We can revisit if this request comes up more often.
