### ISSUE TITLE
Freeze on osx

### ISSUE THREAD

**Issue by rougier** [minad/jinx#48]
I've installed the ELPA version on Emacs+ 28.2 / OSX 13.3.1 and when I try to start jinx-mode, it freezes Emacs. After some investigations, it seems the line `(mapcar #'jinx--mod-dict (split-string jinx-languages)` (in `jinx--load-dicts`) is the culprit but then I'm not sure how to debug from here. Any idea?

**Comment by minad** [comment]
Thank you for trying Jinx and reporting this problem. This has been reported before (#29), but it is unlikely to be a Jinx issue, but rather a problem of Emacs dynamic module support. Unfortunately I cannot help since I don't have access to a Mac. I've also gotten a positive reports about Jinx on Mac (#16), so I wonder what the difference is between your Mac Emacs version and the one used by @sjlambda. I've heard that multiple Mac ports exist. Could you please ask someone knowledge about your Mac port or try to debug this via `gdb`? You could try to obtain a native stack trace to determine where the call is hanging - likely in code outside of the control of Jinx.

**Comment by rougier** [comment]
Thanks, didn't see the previous issues. I'll try to debug.

**Comment by minad** [comment]
Thanks, also don't hesitate to report this upstream to the Mac maintainer. jinx-mod.c is a pretty small and simple Emacs module. It should be relatively easy to reproduce the problem.

**Comment by rougier** [comment]
Problem disappears with Emacs 30

**Comment by haji-ali** [comment]
On Emacs 29.1, I can see this issue on [emacs-port](https://github.com/railwaycat/homebrew-emacsmacport) but not on [emacs-plus](https://github.com/d12frosted/homebrew-emacs-plus) or GNU Emacs.

I am not sure what the reason is though.

**Comment by minad** [comment]
@haji-ali The issue is described in #91. You can use the workaround documented there.
