### ISSUE TITLE
Feature requests: jinx-save-undo and jinx-visit-personal-dictionary

### ISSUE THREAD

**Issue by ashton314** [minad/jinx#67]
I've accidentally added a word to my personal dictionary when I just meant to save for a session. It would be nice to be able to undo the last stored word and/or visit the personal dictionary file to make direct modifications.

After poking around in the source, this looks like it would have to come from the Enchant library itself, ja? Two functions—`enchant_dict_remove` and `enchant_dict_describe` seem like promising candidates. I'm not familiar with the source though, so take that with a big grain of salt.

**Comment by minad** [comment]
Also note that with the current UI, every save operation requires double confirmation. Correcting words uses single quick keys (1, 2, 3, ...) only, but to save you always have to press @, + or * and then RET as a second key. In my opinion, the protection against mistakes is sufficient. Correcting mistakes which still happen is not extremely convenient, since you have to open the file and restart Emacs. But think about accidentally deleting files in Dired or via Embark - good luck restoring them from backups. There is also not much more confirmation in those cases (except if you also use the move to trash feature).

**Comment by minad** [comment]
I guess I would agree to adding a command jinx-find-personal, however afaik there is no API to obtain the filename. Can you please check if the information is available via the Enchant API?

**Comment by ashton314** [comment]
Hey Daniel, [looks like Enchant 2.5](https://github.com/AbiWord/enchant/issues/329) has an easy-to-find personal dictionary file now. Would you consider re-opening this issue? I might be able to get time to implement `jinx-visit-personal-file` myself later, but I don't have time right this instant.

**Comment by minad** [comment]
Given that the new personal dictionaries have a predictable path, the visit command will be trivial. Maybe add the command to the wiki for now with a warning that it only works with recent Enchant? Or as an even easier alternative put the handful of your dictionaries in file registers. Then you get quick access for free and they will even show up via consult--source-file-register. Wdyt?

(Btw, putting your init.el in a quick access file register is a great trick to boost your Emacs productivity! ;)

**Comment by minad** [comment]
Another thought - given the new personal dictionary handling of Enchant it may be nice if Enchant offered some extra editing API (adding, removing, iterating). Maybe that exists already - I haven't checked? Then we could offer a simple completion interface. Alternatively we could bypass Enchant and access the file directly, but I wouldn't be too fond of that since it would desync the Enchant state. The visit file command suffers from the same problem if you edit the file.
