### ISSUE TITLE
Suggestions from jinx-local-words

### ISSUE THREAD

**Issue by shouya** [minad/jinx#96]
Hi @minad, recently I came to realize that Jinx doesn't include words defined locally in `jinx-correct` suggestions. In comparison, words added to my personal dictionary was suggested as expected.

From what I understood from reading the code, it seems that the local words (which is read into `jinx--session-words`) are used to prevent Jinx from registering these as as invalid words (`jinx--word-valid-p`), but not considered part of a dictionary which Jinx uses for correction.

I reckon there will be an additional advantage of treating session words as in a dictionary other than the ability to make suggestion: it may enable more flexible word forms to be accepted. For example, if I add "eglot" to the personal dictionary, then "Eglot" will no longer count as invalid; but if I instead add "eglot" into local words/session words, then Jinx will still mark the use of "Eglot" as invalid. This behavior discrepancy is a little inconsistent IMO, though it doesn't really bother much.

I'm trying to modify the code for this behavior by making a buffer-local dictionary for `jinx--session-words`, but it seems non-trivial to me. I don't know how it can be done. Could you impart me some suggestions? Thank you!

**Comment by minad** [comment]
Hi @shouya,

yes, I am aware of this shortcoming and I did look into this when developing Jinx. It is a deliberate decision since I want to avoid creating many (per-buffer) dictionary objects. Maybe I am overestimating the effect, but `global-jinx-mode` is basically enabled in every buffer. Generally my projects put focus on saving resources if possible, even if memory and computing power is cheaper these days. That's another reason why to like Emacs and not the most shiny newest Electron editor. ;)

I don't consider the case sensitivity as a problem, also since only one of the forms is to be considered correct. For example the only correct spelling of the name "Eglot" is "Eglot" in English. To come back to the technical reasons - Enchant offers an API which can be used to add per session words to a dictionary:

~~~ c
void enchant_dict_add_to_session (EnchantDict * dict, const char *const word, ssize_t len);
~~~

This means we could in principle add session words to any of the dictionary objects used for all the buffers, but then the session words would be shared, which is likely undesired. This would then mean that we have to duplicate all the dictionary objects to prevent sharing. Unfortunately this has the implication that we also need a separate dictionary broker, since dictionaries are reference counted and shared per broker in Enchant itself. If we would be going that route we would still use one "standard broker" for all the buffers without session words and only create a separate broker and dictionary per-buffer for the session words.

~~~ c
EnchantBroker *enchant_broker_init (void); // Separate broker per buffer
EnchantDict *enchant_broker_request_dict (EnchantBroker * broker, const char *const tag); // Separate dictionary per buffer
void enchant_dict_add_to_session (EnchantDict * dict, const char *const word, ssize_t len);
~~~

Another option would be to create special buffer-local session dictionaries given the one existing broker. Unfortunately Enchant doesn't offer the ideal API for that. One could abuse `enchant_broker_request_pwl_dict` with a temporary word list file which is then deleted afterwards.

~~~ c
EnchantDict *enchant_broker_request_pwl_dict (EnchantBroker * broker, const char *const pwl);
void enchant_dict_add_to_session (EnchantDict * dict, const char *const word, ssize_t len);
~~~

A better hypothetical solution would be offered by an API which allows creation of unshared empty dictionaries, such that we could then add the session words to that dictionary.

~~~ c
EnchantDict *enchant_broker_request_empty_dict (EnchantBroker * broker); // Does not exist :(
void enchant_dict_add_to_session (EnchantDict * dict, const char *const word, ssize_t len);
char **enchant_dict_suggest (EnchantDict * dict, const char *const word,
			     ssize_t len, size_t * out_n_suggs);
~~~

I believe the reason why this API does not exist is that Enchant has to rely on the backend provider to create suggestions from the session dictionary and the personal dictionary. Such an empty dictionary would be backend provider independent and Enchant would have to invent its own algorithm for `enchant_dict_suggest` which will likely be inconsistent with the backend providers. Iirc I've also read somewhere that the handling of personal word lists (pwl) or session words in `enchant_dict_suggest` is problematic or inconsistent, since the personal words lack inflection information. 

For these reasons I decided that it is not worth going to the Enchant level for session words. I think it is also nice to stay on the Elisp level for that and just carry a simple list of words around, given that we can easily inspect and manipulate Elisp variables. This is just less complex and opens up possibilities for tweaks by the user. 

Word tokenization is another example which in Jinx is implemented in Elisp itself, since this opens up more possibilities for mode-specific ignore mechanisms. I opted to solve this on the Elisp level than throwing a whole chunk of text at the backend as is done by other spell checkers. This won't be as good as fancy Unicode Text Segmentation algorithms, but mostly sufficient. Furthermore Enchant also doesn't offer a proper implementation for text segmentation in the backends, such that not much is actually lost.

I hope this explains why things are the way they are.

**Comment by minad** [comment]
Another alternative would be to add the words from `jinx--session-words` to `jinx--correct-suggestions` verbatim without inflection. This is a solution I find more acceptable than using the Enchant API with the aforementioned shortcomings. What do you think?

**Comment by shouya** [comment]
Thanks for your explanation! It makes a lot of senses.

For your idea of modifying `jinx--correct-suggestions`, which sounds a lot practical to implement. It is a very nice suggestion and would indeed satisfy my need. I will later make an attempt to patch `jinx--correct-suggestions` this way.

Moreover, I want to argue a little more on the case for accepting capitalized word. I admit it 'Eglot' was an improper example I gave, since it's a proper noun and should be always capitalized. However, I insist that the point is not disproved by this example. I have encountered cases where a normal word is not in dictionary, but is expected to be capitalized in the beginning of a sentence and lowercased everywhere else. I do agree that this particular capitalizing rule is not universal - languages like German have different rules for casing. Again, I want to emphasize that I'm not bothered at all by this particular nuisance. It seems pretty easy to patch `jinx--word-valid-p` for this purpose if I really want that. Thanks again!

**Comment by minad** [comment]
> For your idea of modifying jinx--correct-suggestions, which sounds a lot practical to implement. It is a very nice suggestion and would indeed satisfy my need. I will later make an attempt to patch jinx--correct-suggestions this way.

Okay, feel free to create a patch! But note the requirement of the FSF copyright assignment. Do you have these papers signed?

> I have encountered cases where a normal word is not in dictionary, but is expected to be capitalized in the beginning of a sentence and lowercased everywhere else.

Right. Capitalized words are usually accepted always because they could stand at the beginning of a sentence. We should probably add a condition to `jinx--word-valid-p`. If the given word is capitalized, check if the non-capitalized variant is a member of `jinx--session-words`.

**Comment by shouya** [comment]
> Okay, feel free to create a patch!

Nice to hear that.  I'll try implement it tomorrow.

> But note the requirement of the FSF copyright assignment. Do you have these papers signed?

I have never contributed to a FSF project before so not yet. But let me write the code first see if it works. And I can sign it later if necessary.

> We should probably add a condition to `jinx--word-valid-p`.

I'm not sure. I worry that one may add the capitalized word into dictionary on its the first occurrence, but then a valid capitalized word doesn't imply the lowercase word is valid, too. In that case he may run into the need of adding the lowercase word as well, resulting a redundant capitalized word entry. This can feel a little inconsistent from the user's perspective. But again, any attempt to define a rule on languages is almost bound to be inaccurate in some way, so perhaps a practical solution is good enough.

**Comment by minad** [comment]
> I have never contributed to a FSF project before so not yet. But let me write the code first see if it works. And I can sign it later if necessary.

Sure. If your contribution is below 15 lines we can also add it directly without assignment, since then it is considered trivial enough.

> I worry that one may add the capitalized word into dictionary on its the first occurrence, but then a valid capitalized word doesn't imply the lowercase word is valid, too.

Yes. The check I've added only considers capitalized words as valid if the lower case form is included in the session words. Not the other way round.
